var searchData=
[
  ['h_5fd_5fa_0',['h_d_A',['../classdftfe_1_1kohn_sham_d_f_t_operator_c_u_d_a_class.html#afe63e92ef6dd3ca69a0e74c9c8cf1d69',1,'dftfe::kohnShamDFTOperatorCUDAClass']]],
  ['h_5fd_5fb_1',['h_d_B',['../classdftfe_1_1kohn_sham_d_f_t_operator_c_u_d_a_class.html#affbae0835a3103975e4040b4a54d753a',1,'dftfe::kohnShamDFTOperatorCUDAClass']]],
  ['h_5fd_5fc_2',['h_d_C',['../classdftfe_1_1kohn_sham_d_f_t_operator_c_u_d_a_class.html#a63be213248f02d0c0f95aa83cfb1d1f5',1,'dftfe::kohnShamDFTOperatorCUDAClass']]],
  ['haperbohrtoevperang_3',['haPerBohrToeVPerAng',['../classdftfe_1_1molecular_dynamics_class.html#ae6facb80fc18889cada2d2f0b548527d',1,'dftfe::molecularDynamicsClass']]],
  ['hatoev_4',['haToeV',['../classdftfe_1_1molecular_dynamics_class.html#aa4ff0cbe5e3e00d1b3284d9fbdf3a5b5',1,'dftfe::molecularDynamicsClass']]],
  ['headers_2eh_5',['headers.h',['../headers_8h.html',1,'']]],
  ['hermitian_6',['hermitian',['../namespacedftfe_1_1_l_a_p_a_c_k_support.html#af3c45dcea64890f047b4dca87fdde9acacb022b5e749ecd8aded585fa69365425',1,'dftfe::LAPACKSupport']]],
  ['hessenberg_7',['hessenberg',['../namespacedftfe_1_1_l_a_p_a_c_k_support.html#af3c45dcea64890f047b4dca87fdde9aca7c62e84843fe08403ca442daf6d76bd3',1,'dftfe::LAPACKSupport']]],
  ['host_8',['Host',['../structdftfe_1_1_memory_space_1_1_host.html',1,'dftfe::MemorySpace']]],
  ['hvec_9',['hvec',['../classdftfe_1_1dealii_linear_solver.html#acb4b656e30476b8c7d49347ceafbba60',1,'dftfe::dealiiLinearSolver']]],
  ['hx_10',['HX',['../classdftfe_1_1kohn_sham_d_f_t_operator_class.html#ab2864c2e7469ffbb07e4af4b67072cbf',1,'dftfe::kohnShamDFTOperatorClass::HX(distributedCPUVec&lt; dataTypes::number &gt; &amp;src, const unsigned int numberComponents, const bool scaleFlag, const double scalar, distributedCPUVec&lt; dataTypes::number &gt; &amp;dst)'],['../classdftfe_1_1kohn_sham_d_f_t_operator_class.html#ab5ceee26c206b04a0927dbbdf8122144',1,'dftfe::kohnShamDFTOperatorClass::HX(distributedCPUVec&lt; dataTypes::number &gt; &amp;src, std::vector&lt; dataTypes::number &gt; &amp;cellSrcWaveFunctionMatrix, const unsigned int numberComponents, const bool scaleFlag, const double scalar, const double scalarA, const double scalarB, distributedCPUVec&lt; dataTypes::number &gt; &amp;dst, std::vector&lt; dataTypes::number &gt; &amp;cellDstWaveFunctionMatrix)'],['../classdftfe_1_1kohn_sham_d_f_t_operator_c_u_d_a_class.html#a43a71fdd9413cc3f8a6f977fd4d90b90',1,'dftfe::kohnShamDFTOperatorCUDAClass::HX(distributedGPUVec&lt; dataTypes::numberGPU &gt; &amp;src, distributedGPUVec&lt; dataTypes::numberGPU &gt; &amp;projectorKetTimesVector, const unsigned int localVectorSize, const unsigned int numberComponents, const bool scaleFlag, const double scalar, distributedGPUVec&lt; dataTypes::numberGPU &gt; &amp;dst, const bool doUnscalingX=true)'],['../classdftfe_1_1kohn_sham_d_f_t_operator_c_u_d_a_class.html#aadebe2c2c0ab0709d83696fa6a370334',1,'dftfe::kohnShamDFTOperatorCUDAClass::HX(distributedGPUVec&lt; dataTypes::numberGPU &gt; &amp;src, distributedGPUVec&lt; dataTypes::numberFP32GPU &gt; &amp;srcFloat, distributedGPUVec&lt; dataTypes::numberGPU &gt; &amp;projectorKetTimesVector, const unsigned int localVectorSize, const unsigned int numberComponents, const bool scaleFlag, const double scalar, distributedGPUVec&lt; dataTypes::numberGPU &gt; &amp;dst, const bool doUnscalingX=true, const bool singlePrecCommun=false)'],['../classdftfe_1_1operator_d_f_t_class.html#a3e9854c31734c593ce891c8bc371e9e7',1,'dftfe::operatorDFTClass::HX(distributedCPUVec&lt; dataTypes::number &gt; &amp;X, const unsigned int numberComponents, const bool scaleFlag, const double scalar, distributedCPUVec&lt; dataTypes::number &gt; &amp;Y)=0'],['../classdftfe_1_1operator_d_f_t_class.html#ac62306ff1722c3def72ab5a4beadc095',1,'dftfe::operatorDFTClass::HX(distributedCPUVec&lt; dataTypes::number &gt; &amp;src, std::vector&lt; dataTypes::number &gt; &amp;cellSrcWaveFunctionMatrix, const unsigned int numberWaveFunctions, const bool scaleFlag, const double scalar, const double scalarA, const double scalarB, distributedCPUVec&lt; dataTypes::number &gt; &amp;dst, std::vector&lt; dataTypes::number &gt; &amp;cellDstWaveFunctionMatrix)=0']]],
  ['hxcheby_11',['HXCheby',['../classdftfe_1_1kohn_sham_d_f_t_operator_c_u_d_a_class.html#a0795a3e726af1dc6a82165d47b2ffb6b',1,'dftfe::kohnShamDFTOperatorCUDAClass']]],
  ['hxoptimflag_12',['HXOptimFlag',['../classdftfe_1_1dft_parameters.html#a2d253b597ded056bd5f971df0fa4db4a',1,'dftfe::dftParameters']]]
];
