var searchData=
[
  ['xcopy_0',['xcopy',['../namespacedftfe.html#a0d322b954a8fb2c1281080253b7a82d2',1,'dftfe::xcopy(const unsigned int *n, const double *x, const unsigned int *incx, double *y, const unsigned int *incy)'],['../namespacedftfe.html#a4b20c20260a74738a998d138a073c159',1,'dftfe::xcopy(const unsigned int *n, const std::complex&lt; double &gt; *x, const unsigned int *incx, std::complex&lt; double &gt; *y, const unsigned int *incy)']]],
  ['xgemm_1',['xgemm',['../namespacedftfe.html#a828f84688b0712b000dc44a95959d8e1',1,'dftfe::xgemm(const char *transA, const char *transB, const unsigned int *m, const unsigned int *n, const unsigned int *k, const double *alpha, const double *A, const unsigned int *lda, const double *B, const unsigned int *ldb, const double *beta, double *C, const unsigned int *ldc)'],['../namespacedftfe.html#a2dadfd9db8344c3f3678dec16f847ac1',1,'dftfe::xgemm(const char *transA, const char *transB, const unsigned int *m, const unsigned int *n, const unsigned int *k, const float *alpha, const float *A, const unsigned int *lda, const float *B, const unsigned int *ldb, const float *beta, float *C, const unsigned int *ldc)'],['../namespacedftfe.html#aa8e18f003e5d8812e4010339fff58b2f',1,'dftfe::xgemm(const char *transA, const char *transB, const unsigned int *m, const unsigned int *n, const unsigned int *k, const std::complex&lt; double &gt; *alpha, const std::complex&lt; double &gt; *A, const unsigned int *lda, const std::complex&lt; double &gt; *B, const unsigned int *ldb, const std::complex&lt; double &gt; *beta, std::complex&lt; double &gt; *C, const unsigned int *ldc)'],['../namespacedftfe.html#aef71ffd789e0a80b219b0a56927b135a',1,'dftfe::xgemm(const char *transA, const char *transB, const unsigned int *m, const unsigned int *n, const unsigned int *k, const std::complex&lt; float &gt; *alpha, const std::complex&lt; float &gt; *A, const unsigned int *lda, const std::complex&lt; float &gt; *B, const unsigned int *ldb, const std::complex&lt; float &gt; *beta, std::complex&lt; float &gt; *C, const unsigned int *ldc)']]],
  ['xmltodftfeparser_2',['xmlTodftfeParser',['../classdftfe_1_1pseudo_utils_1_1xml_todftfe_parser.html#a289dbe12684054f78dcaf0a5cad4f02a',1,'dftfe::pseudoUtils::xmlTodftfeParser']]],
  ['xscal_3',['xscal',['../namespacedftfe.html#a28ef5d3da7aac5f881ec00d1a40d5614',1,'dftfe::xscal(const unsigned int *n, const double *alpha, double *x, const unsigned int *inc)'],['../namespacedftfe.html#ad580fa3f6ab6426c92d6818b2326803d',1,'dftfe::xscal(const unsigned int *n, const std::complex&lt; double &gt; *alpha, std::complex&lt; double &gt; *x, const unsigned int *inc)']]],
  ['xthx_4',['XtHX',['../classdftfe_1_1kohn_sham_d_f_t_operator_class.html#a715650cf94ebbe77642965cb41475dde',1,'dftfe::kohnShamDFTOperatorClass::XtHX(const std::vector&lt; dataTypes::number &gt; &amp;src, const unsigned int numberComponents, std::vector&lt; dataTypes::number &gt; &amp;ProjHam)'],['../classdftfe_1_1kohn_sham_d_f_t_operator_class.html#af8d14666e71e2192d94519e2f778ad94',1,'dftfe::kohnShamDFTOperatorClass::XtHX(const std::vector&lt; dataTypes::number &gt; &amp;X, const unsigned int numberComponents, const std::shared_ptr&lt; const dftfe::ProcessGrid &gt; &amp;processGrid, dftfe::ScaLAPACKMatrix&lt; dataTypes::number &gt; &amp;projHamPar)'],['../classdftfe_1_1operator_d_f_t_class.html#aab3b9eb1cce4ac020d9e50f03cd950b3',1,'dftfe::operatorDFTClass::XtHX(const std::vector&lt; dataTypes::number &gt; &amp;X, const unsigned int numberComponents, std::vector&lt; dataTypes::number &gt; &amp;ProjHam)=0'],['../classdftfe_1_1operator_d_f_t_class.html#af2b3eec3942f288124630e6c16b0426e',1,'dftfe::operatorDFTClass::XtHX(const std::vector&lt; dataTypes::number &gt; &amp;X, const unsigned int numberComponents, const std::shared_ptr&lt; const dftfe::ProcessGrid &gt; &amp;processGrid, dftfe::ScaLAPACKMatrix&lt; dataTypes::number &gt; &amp;projHamPar)=0']]],
  ['xthxmixedprec_5',['XtHXMixedPrec',['../classdftfe_1_1kohn_sham_d_f_t_operator_class.html#a3d27521f7b616b68234fc77c79027f63',1,'dftfe::kohnShamDFTOperatorClass::XtHXMixedPrec()'],['../classdftfe_1_1operator_d_f_t_class.html#ace76dfe771dfe5d016e962a8126569a1',1,'dftfe::operatorDFTClass::XtHXMixedPrec()']]]
];
